version: "3"

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1-arm64
        environment:
            - node.name=es01
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - 9200:9200
            - 9300:9300
        volumes:
            - es-data:/usr/share/elasticsearch/data
        networks:
            - elastic
    kibana:
        image: docker.elastic.co/kibana/kibana:7.15.1-arm64
        environment:
            - "ELASTICSEARCH_HOSTS=http:/elasticsearch:9200"
        ports:
            - 5601:5601
        networks:
            - elastic
volumes:
    es-data:
        driver: local
networks:
    elastic:
        driver: bridge
